version: 2
sphinx:
   builder: html
   configuration: docs/source/conf.py
   fail_on_warning: false  # Temporarily disable due to citation warning
python:
   version: 3.8
   system_packages: true
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
